In [1]:
import sys

In [2]:
print(sys.version)

3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]


In [3]:
import platform

In [4]:
platform.python_version()

'3.8.8'

In [5]:
print('Hello World')

Hello World


In [6]:
x = 3
print(type(x))

<class 'int'>


In [7]:
y = float(x)
y

3.0

In [8]:
a = 30

In [10]:
distance = [10,15,17,26]
time = [.30,0.47,0.55,1.20]

In [11]:
speed = distance/time

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [13]:
import numpy as np

In [14]:
np_distance = np.array(distance)
np_time = np.array(time)

In [16]:
np_speed = np_distance/np_time
np_speed

array([33.33333333, 31.91489362, 30.90909091, 21.66666667])

In [17]:
#Creating an arrays with zeros
array_with_zeros = np.zeros((3,3))
array_with_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
array_with_ones = np.ones((3,3))
array_with_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
empty_array= np.empty((2,3))
empty_array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
# arange method
np_arange = np.arange(12)
np_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [22]:
np_arange.reshape(3,4) #To reshape an array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
#linspace
np_linspace = np.linspace(1,6,5) #np.linspace(start, end, no of evenly spaced elements)
np_linspace

array([1.  , 2.25, 3.5 , 4.75, 6.  ])

In [26]:
# 1D, 2D and 3D arrays
oneD = np.arange (15)
print(oneD)
twoD = oneD.reshape(3,5)
print(twoD)
threeD = np.arange(27).reshape(3,3,3)
print(threeD)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [27]:
#Ndim shows the dimension of the array
city = np.array(['NYC','LA','Miami','Houston'])
city.ndim

1

In [28]:
city_state = np.array([['NYC', 'LA','Miami','Houston'],['NY','CA','FL','TX']])
city_state.ndim

2

In [29]:
#ndarray.shape
city.shape

(4,)

In [30]:
city_state.shape

(2, 4)

In [31]:
#ndarray.size
city.size

4

In [32]:
city_state.size

8

In [33]:
#ndarray.dtype
city_state.dtype

dtype('<U7')

Basic Operations

In [34]:
#addition
np.add(40,50)

90

In [35]:
#Subtraction
np.subtract(50,40)

10

In [36]:
#ndarray multiplication
hourly_wage =np.array([7,10,9,11,15,12])*15
print(hourly_wage)

[105 150 135 165 225 180]


In [37]:
#total earings after 6 days
sum(hourly_wage)

960

Comparison Operators

In [42]:
marks =np.array([60,67, 87, 93, 67, 75, 88, 98, 89])
marks[marks!=75] #(<,>,==,!=)

array([60, 67, 87, 93, 67, 88, 98, 89])

Logical Operations

In [46]:
#np.logical_and (for more than one condition)
np.logical_and(marks>65,marks<90)

array([False,  True,  True, False,  True,  True,  True, False,  True])

In [47]:
#np.logical_not(for using conditions like not greater than, not less than,not equal to)
np.logical_not(marks>=75)

array([ True,  True, False, False,  True, False, False, False, False])

Accessing Array elements (Indexing)

In [52]:
cyclist_trials = np.array([[10,15,17, 26],[12,11,21,24]])
first_trial = cyclist_trials[0][2]
print(first_trial)
second_trial = cyclist_trials[1]
print(second_trial)

17
[12 11 21 24]
