In [74]:
import sys

In [75]:
print(sys.version)

3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]


In [76]:
import platform

In [77]:
platform.python_version()

'3.8.8'

In [78]:
print('Hello World')

Hello World


In [79]:
x = 3
print(type(x))

<class 'int'>


In [80]:
y = float(x)
y

3.0

In [81]:
a = 30

In [82]:
distance = [10,15,17,26]
time = [.30,0.47,0.55,1.20]

In [83]:
speed = distance/time

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [84]:
import numpy as np

In [85]:
np_distance = np.array(distance)
np_time = np.array(time)

In [86]:
np_speed = np_distance/np_time
np_speed

array([33.33333333, 31.91489362, 30.90909091, 21.66666667])

In [87]:
#Creating an arrays with zeros
array_with_zeros = np.zeros((3,3))
array_with_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [88]:
array_with_ones = np.ones((3,3))
array_with_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [89]:
empty_array= np.empty((2,3))
empty_array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [90]:
# arange method
np_arange = np.arange(12)
np_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [91]:
np_arange.reshape(3,4) #To reshape an array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [92]:
#linspace
np_linspace = np.linspace(1,6,5) #np.linspace(start, end, no of evenly spaced elements)
np_linspace

array([1.  , 2.25, 3.5 , 4.75, 6.  ])

In [93]:
# 1D, 2D and 3D arrays
oneD = np.arange (15)
print(oneD)
twoD = oneD.reshape(3,5)
print(twoD)
threeD = np.arange(27).reshape(3,3,3)
print(threeD)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [94]:
#Ndim shows the dimension of the array
city = np.array(['NYC','LA','Miami','Houston'])
city.ndim

1

In [95]:
city_state = np.array([['NYC', 'LA','Miami','Houston'],['NY','CA','FL','TX']])
city_state.ndim

2

In [96]:
#ndarray.shape
city.shape

(4,)

In [97]:
city_state.shape

(2, 4)

In [98]:
#ndarray.size
city.size

4

In [99]:
city_state.size

8

In [100]:
#ndarray.dtype
city_state.dtype

dtype('<U7')

Basic Operations

In [101]:
#addition
np.add(40,50)

90

In [102]:
#Subtraction
np.subtract(50,40)

10

In [103]:
#ndarray multiplication
hourly_wage =np.array([7,10,9,11,15,12])*15
print(hourly_wage)

[105 150 135 165 225 180]


In [104]:
#total earings after 6 days
sum(hourly_wage)

960

Comparison Operators

In [105]:
marks =np.array([60,67, 87, 93, 67, 75, 88, 98, 89])
marks[marks!=75] #(<,>,==,!=)

array([60, 67, 87, 93, 67, 88, 98, 89])

Logical Operations

In [106]:
#np.logical_and (for more than one condition)
np.logical_and(marks>65,marks<90)

array([False,  True,  True, False,  True,  True,  True, False,  True])

In [107]:
#np.logical_not(for using conditions like not greater than, not less than,not equal to)
np.logical_not(marks>=75)

array([ True,  True, False, False,  True, False, False, False, False])

Accessing Array elements (Indexing)

In [108]:
cyclist_trials = np.array([[10,15,17, 26],[12,11,21,24]])
first_trial = cyclist_trials[0][2]
print(first_trial)
second_trial = cyclist_trials[1]
print(second_trial)
two_cyclist_data =cyclist_trials[:,1:3]
print(two_cyclist_data)

17
[12 11 21 24]
[[15 17]
 [11 21]]


In [109]:
for iterate in cyclist_trials:
    print(iterate)
    new = iterate * 2
    print(new)

[10 15 17 26]
[20 30 34 52]
[12 11 21 24]
[24 22 42 48]


Indexing with Boolean Arrays

In [110]:
scores = np.array([[83,71,57,63],[54,68,81,45]])
passing_score = scores>60
passing_score

array([[ True,  True, False,  True],
       [False,  True,  True, False]])

In [111]:
scores[passing_score]

array([83, 71, 63, 68, 81])

Copy and Views

In [112]:
NYC_Borough = np.array(['Manhattan','Bronx','Brooklyn','Staten Island','Queens'])
NYC_Borough

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Island', 'Queens'],
      dtype='<U13')

In [113]:
Borough_in_NYC = NYC_Borough
Borough_in_NYC

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Island', 'Queens'],
      dtype='<U13')

In [114]:
Borough_in_NYC is NYC_Borough

True

In [115]:
view_of_Borough_in_NYC = Borough_in_NYC.view()
view_of_Borough_in_NYC

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Island', 'Queens'],
      dtype='<U13')

In [116]:
len(view_of_Borough_in_NYC)

5

In [117]:
view_of_Borough_in_NYC[4]='Central Park' #Changing Value in view object changes the value in original Data Set
view_of_Borough_in_NYC

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Island', 'Central Park'],
      dtype='<U13')

In [118]:
Borough_in_NYC

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Island', 'Central Park'],
      dtype='<U13')

In [119]:
copy_of_NYC_Borough = NYC_Borough.copy()
copy_of_NYC_Borough

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Island', 'Central Park'],
      dtype='<U13')

In [120]:
copy_of_NYC_Borough is NYC_Borough 
#Even though copy is exactly same as original, the values is False as it is treated different.

False

In [121]:
NYC_Borough.base is NYC_Borough
#Shows 'copy' object data is not owned by the original Dataset

False

In [124]:
copy_of_NYC_Borough[4] ='Central Park'
copy_of_NYC_Borough

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Island', 'Central Park'],
      dtype='<U13')

# Mathemathical Functions

NumPy provides useful mathematical functions, which are called Universal Functions.\
These functions operate element-wiseon an array, producing another array as output.\
Some of the functions are listed below:-

sqrt functions provides the squareroot of every element in the array.\
cos function provides the cosine value for every element in the array.\
floor function returns the largest integer value of the every element in the array.\
exp function performs exponentiation on each element of the array.

In [127]:
np_sqrt = np.sqrt([1,2,3,4,5])
np_sqrt

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [128]:
from numpy import pi
np.cos(5)

0.28366218546322625

In [130]:
np.sin(pi/2)

1.0

In [131]:
np.cos(pi)

-1.0

In [132]:
np.floor([1.5,1.6, 2.6, 3.5, 4.8, 5.0, 6.34, 7.4])


array([1., 1., 2., 3., 4., 5., 6., 7.])

In [133]:
np.exp([0,1,3])

array([ 1.        ,  2.71828183, 20.08553692])

Shape Manipulation.\
Certain following methods can be used to manipulate the shape of an array.

In [135]:
new_cyclist_trials = np.array([[10,15,17,26,13,19],[12,11,21,24,14,23]])

In [136]:
new_cyclist_trials.ravel()
#ravel function joins the multi dimention array into one single dimentions array. Flattens the Dataset

array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 23])

In [144]:
new_cyclist_trials.reshape(3,2,2)
#reshape functions reshapes array into specified array type.Changes the shape of the dataset

array([[[10, 15],
        [17, 26]],

       [[13, 19],
        [12, 11]],

       [[21, 24],
        [14, 23]]])

In [151]:
new_cyclist_trials.resize(2,6)
new_cyclist_trials 
#Resizes the Data set

array([[10, 15, 17, 26, 13, 19],
       [12, 11, 21, 24, 14, 23]])

In [160]:
np.hsplit(new_cyclist_trials,2)
#splits the array into specified nomber of arrays, in the case its 2

[array([[10, 15, 17],
        [12, 11, 21]]),
 array([[26, 13, 19],
        [24, 14, 23]])]

In [161]:
new_cyclist_trials = np.array([[10,15,17,26,13,19],[12,11,21,24,14,23]])
cyclist_1 = new_cyclist_trials[0]
cyclist_2 =new_cyclist_trials[1]
print('cyclist_1 = ',cyclist_1)
print('cyclist_2 =', cyclist_2)

cyclist_1 =  [10 15 17 26 13 19]
cyclist_2 = [12 11 21 24 14 23]


In [162]:
np.hstack((cyclist_1,cyclist_2))
#Stacks multiple arrays together.

array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 23])

# Broadcasting.
Numpy used Broadcasting to carry out Arithmetic operations between arrays of different shapes.\
In this method NumPy automatically broadcasts the smaller array over the larger array.

In [163]:
#Creating arrays of same shape
a = np.array([2,3,4,5])
b = np.array([.3,.3,.5,.6])
a*b

array([0.6, 0.9, 2. , 3. ])

In [164]:
# a and c are of different shapes, so broadcasting multiplies the entire array a with the scalar c
c = .2
a*c

array([0.4, 0.6, 0.8, 1. ])

Broadcasting has its own limitations.\
Though broadcasting can help carry out mathematical operation between different shaped arrays, it is subject to certain constraints as listed below:\
When NumPy operates on two arrays, it compares theier shapes elementwise, It finds these shapes compatible only if :\
Their dimensions are same, or \
One of then has a dimension of 1

In [165]:
week_1 = np.array([105,135,195,120,165])
week_2 = np.array([123,156,230,200,147])
total_earnings = week_1 + week_2  #Element wise operation
total_earnings  #Total Earnings for 2 weeks.

array([228, 291, 425, 320, 312])

In [168]:
week_1_hrs = week_1/15 #15 is the rate per hour
week_1_hrs  #1st week working hours

array([ 7.,  9., 13.,  8., 11.])

Linera Algebra - Transpose.\
NumPy can carry out Linear Algebric functions as well.\
The 'transpose()' function can help you interchange rows and columns, and vice-versa

In [169]:
test_scores = np.array([[83,71,57,63],[54,68,81,45]])
test_scores

array([[83, 71, 57, 63],
       [54, 68, 81, 45]])

In [171]:
test_scores.transpose()

array([[83, 54],
       [71, 68],
       [57, 81],
       [63, 45]])

Inverse and Trace functions.\
*np.linalg.inv()* \
Using NumPy, you can also findthe inverse of an array and add its diagonal data elements.\
Inverse function can only be applied to square matrix.\
*np.trace()* \
Trace function helps you perform sumon the diagonal elements in the array. \
trace() function is only used for diagonals.
Its an incremental order and applied only from left to right and not vice-versa.

In [173]:
inverse_array = np.array([[10,20],[15,25]])
np.linalg.inv(inverse_array)

array([[-0.5,  0.4],
       [ 0.3, -0.2]])

In [174]:
trace_array = np.array([[10,20],[15,25]])
np.trace(trace_array)

35